# Site settings
title: David Zhang
author: David Zhang
description: "A minimalist programmer, photographer, and lifehacker. Blog, project, wiki, and about."
url: "https://crispgm.com"
alt_url: "https://crisp.lol"
encoding: utf-8
markdown: kramdown
assets: /assets

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
      syntax_highlight: false

# Contacts
contact:
  email: crispgm@gmail.com
  github: crispgm
  instagram: crispgm
  twitter: crispgm
  stack_overflow: 6858150/david-zhang

# Applications
ga:
  tracking_id: UA-50708664-1
disqus:
  short_name: crispgm

# Inclusion
include:
  - _redirects

# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
